export const randomPrompts = [
    "A futuristic cityscape at sunset with towering crystalline skyscrapers.",
    "A mystical forest where the trees emit a soft, enchanting glow.",
    "An underwater metropolis with bioluminescent sea creatures and vibrant coral architecture.",
    "A steampunk-style airship soaring above a vast desert landscape.",
    "A whimsical carnival on the back of a giant turtle, floating through the sky.",
    "A cybernetic dragon guarding a hidden cache of ancient knowledge.",
    "An abandoned space station orbiting a distant and mysterious planet.",
    "A group of adventurers navigating through a labyrinth of floating islands.",
    "A serene garden where plants bloom with music instead of flowers.",
    "A time-traveling explorer witnessing the construction of an ancient wonder.",
    "A post-apocalyptic world where nature has reclaimed a modern city.",
    "A portal opening to a realm of floating islands and flying whales.",
    "A secret library hidden within the roots of an enormous tree.",
    "A hidden underwater cave filled with glowing crystals and aquatic creatures.",
    "A futuristic train speeding through a canyon carved by neon-colored rivers.",
    "A celestial being crafting constellations in the night sky.",
    "A sprawling tree city inhabited by creatures of all shapes and sizes.",
    "A journey across the rings of a gas giant, revealing breathtaking landscapes.",
    "A mechanical forest where robotic animals roam freely.",
    "An ancient temple nestled within the heart of a lush, sentient jungle.",
    "A city of living crystals where light refracts and creates mesmerizing patterns.",
    "A portal that leads to a dimension of floating islands and gravity-defying waterfalls.",
    "A glacial fortress inhabited by ice giants and frosty creatures.",
    "A massive library filled with books that come to life when opened.",
    "A network of underground tunnels illuminated by luminescent fungi.",
    "A serene village on the back of a colossal, slumbering creature.",
    "A cityscape seen through the eyes of a mechanical owl perched on a rooftop.",
    "A futuristic garden where plants are tended to by tiny robotic caretakers.",
    "A colony on a distant planet with gravity-defying flora and fauna.",
    "An ancient observatory atop a mountain, connecting the stars to forgotten legends."
];
  